/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package trabalho.IU;

import java.util.ArrayList;
import trabalho.controlador.Controlador;
import trabalho.modelo.Departamento;
import trabalho.modelo.Funcionario;

/**
 *
 * @author vitor
 */
public class IUCadastroDocenteSubstituto extends javax.swing.JDialog {

    /**
     * Creates new form IUCadastroTecnico
     */
    public IUCadastroDocenteSubstituto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        Mensagem.setText("");
        
        Controlador control = new Controlador();
        ArrayList<Departamento> deptos = control.getDeptos();
        
        for(int i=0; i < deptos.size(); i++){
            DeptosCombo.addItem(deptos.get(i).getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Codigo = new javax.swing.JLabel();
        NomeField = new javax.swing.JTextField();
        Nome = new javax.swing.JLabel();
        CodigoField = new javax.swing.JTextField();
        Salario = new javax.swing.JLabel();
        SalarioField = new javax.swing.JTextField();
        Titulacao = new javax.swing.JLabel();
        Nivel = new javax.swing.JLabel();
        NivelCombo = new javax.swing.JComboBox<>();
        Mensagem = new javax.swing.JLabel();
        Adicionar = new javax.swing.JButton();
        DeptosCombo = new javax.swing.JComboBox<>();
        DeptosFunc = new javax.swing.JLabel();
        TitulacaoCombo = new javax.swing.JComboBox<>();
        CargaHoraria = new javax.swing.JLabel();
        CargaCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar novo docente substituto");

        Codigo.setText("Código do Funcionário");

        Nome.setText("Nome do Funcionário");

        CodigoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CodigoFieldFocusLost(evt);
            }
        });
        CodigoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoFieldActionPerformed(evt);
            }
        });

        Salario.setText("Salário do Funcionário");

        Titulacao.setText("Titulação do Funcionário");

        Nivel.setText("Nível do Funcionário");

        NivelCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S1", "S2" }));
        NivelCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NivelComboActionPerformed(evt);
            }
        });

        Mensagem.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        Mensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mensagem.setText("MENSAGEM");

        Adicionar.setText("Adicionar");
        Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarActionPerformed(evt);
            }
        });

        DeptosFunc.setText("Departamentos do Funcionário");

        TitulacaoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Graduação", "Mestrado", "Doutorado", "Livre-Docente", "Titular" }));
        TitulacaoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitulacaoComboActionPerformed(evt);
            }
        });

        CargaHoraria.setText("Carga Horária do Funcionário");

        CargaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "24" }));
        CargaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargaComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NomeField)
                    .addComponent(Codigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CodigoField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Salario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SalarioField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DeptosFunc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(DeptosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(Adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Titulacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TitulacaoCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 171, Short.MAX_VALUE)
                                .addComponent(Nivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(NivelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CargaCombo, 0, 171, Short.MAX_VALUE)
                            .addComponent(CargaHoraria)
                            .addComponent(Mensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(31, 31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Titulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TitulacaoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CargaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NivelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeptosFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalarioField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeptosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarActionPerformed
        // TODO add your handling code here:
        Controlador control = new Controlador();
        String nome = NomeField.getText();
        String codigo = CodigoField.getText();
        double salario = Double.parseDouble(SalarioField.getText());
        String titulacao = (String) TitulacaoCombo.getSelectedItem();
        String nivel = (String) NivelCombo.getSelectedItem();
        int indice = (int) DeptosCombo.getSelectedIndex();
        int cargaHoraria = Integer.parseInt((String) CargaCombo.getSelectedItem());
        control.addDocenteSubstituto(codigo, nome, salario, nivel, titulacao, cargaHoraria, indice);
        Mensagem.setText("<html><div style='text-align:center'>DOCENTE<br/>CADASTRADO<br/>COM SUCESSO!</div></html>");
        Mensagem.setVisible(true);
        Adicionar.setEnabled(false);
    }//GEN-LAST:event_AdicionarActionPerformed

    private void CodigoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoFieldActionPerformed

    private void CodigoFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CodigoFieldFocusLost
        // TODO add your handling code here:
        String codigo = CodigoField.getText();
        Controlador control = new Controlador();
        Funcionario t = control.buscarFuncCodigo(codigo);
        if(t != null){
            CodigoField.setText(t.getCodigo());
            NomeField.setText(t.getNome());
            SalarioField.setText(String.valueOf(t.getSalario()));
            Mensagem.setText("<html><div style='text-align:center'>FUNCIONÁRIO JÁ<br/>CADASTRADO!</div></html>");
            Mensagem.setVisible(true);
            Adicionar.setEnabled(false);
        }else{
            NomeField.setText("");
            SalarioField.setText("");
            Adicionar.setEnabled(true);
        }
    }//GEN-LAST:event_CodigoFieldFocusLost

    private void NivelComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NivelComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NivelComboActionPerformed

    private void TitulacaoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitulacaoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TitulacaoComboActionPerformed

    private void CargaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargaComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CargaComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUCadastroDocenteSubstituto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUCadastroDocenteSubstituto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUCadastroDocenteSubstituto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUCadastroDocenteSubstituto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IUCadastroDocenteSubstituto dialog = new IUCadastroDocenteSubstituto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        dialog.dispose();
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adicionar;
    private javax.swing.JComboBox<String> CargaCombo;
    private javax.swing.JLabel CargaHoraria;
    private javax.swing.JLabel Codigo;
    private javax.swing.JTextField CodigoField;
    private javax.swing.JComboBox<String> DeptosCombo;
    private javax.swing.JLabel DeptosFunc;
    private javax.swing.JLabel Mensagem;
    private javax.swing.JLabel Nivel;
    private javax.swing.JComboBox<String> NivelCombo;
    private javax.swing.JLabel Nome;
    private javax.swing.JTextField NomeField;
    private javax.swing.JLabel Salario;
    private javax.swing.JTextField SalarioField;
    private javax.swing.JLabel Titulacao;
    private javax.swing.JComboBox<String> TitulacaoCombo;
    // End of variables declaration//GEN-END:variables
}
